name: Lint Ruby

on:
  push:
    branches:
      - main
    paths:
      - "gemfiles/*"
      - "Gemfile"
      - "**/*.rb"
      - "**/*.gemspec"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "gemfiles/*"
      - "Gemfile"
      - "**/*.rb"
      - "**/*.gemspec"
      - ".github/workflows/lint.yml"

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: Lint Ruby code with RuboCop
        run: |
          bundle exec rubocop
